name: Google News Scraper
on:
  schedule:
    - cron: '18 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List directory contents
        run: |
          pwd
          ls -la
          ls -la news_json || echo "news_json directory not found"
          find . -type f

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python Google_Crawler.py
        continue-on-error: true

      - name: Commit and push results
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add news_json/google_News.json
          git commit -m "Update news_json/google_News.json $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
