name: News Crawler

on:
  schedule:
    - cron: '*/5 * * * *' # 매 5분마다 실행
  workflow_dispatch: # 수동 실행 옵션

jobs:
  crawl-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run crawler script
        run: python crawler.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add news.json
          git commit -m "Update news.json with latest news" || echo "No changes to commit"
          git push
