name: SkyDaily News Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # 매일 UTC 08:00 (KST 17:00)에 실행
  workflow_dispatch:     # 수동 실행 가능

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List directory contents
        run: |
          pwd
          ls -la
          find . -type f

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python SkyDaily_Crawler.py
        continue-on-error: true

      - name: Commit and push results
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add skyDaily_News.json
          git commit -m "Update skyDaily_News.json $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
